PINBOT = {"TOKEN":""}
PINBOT["ACK_TYPE"] = "react"
PINBOT["PREFIX"] = ",,"
PINBOT["PINMAP"] = {}
PINBOT["DEFAULT_OUT"] = "inplace"
PINBOT["PIN_THRESHOLD"] = 35
PINBOT["EMBED_COLOR_CALC"] = False
PINBOT["ALLOWED_IDS"] = []